services:
  backend:
    build:
      context: ${API_PATH}
      dockerfile: Dockerfile
    environment:
      - APP_HOST=${APP_HOST}
      - POSTGRES_URL=${POSTGRES_URL}
      - ACCESS_SECRET_KEY=${ACCESS_SECRET_KEY}
  frontend:
    build:
      context: ${APP_PATH}
      dockerfile: Dockerfile
      target: builder
      args:
        API_HOST: ${API_HOST}
  nginx:
    build:
      context: ${APP_PATH}
      dockerfile: Dockerfile
      target: prod
      args:
        API_HOST: ${API_HOST}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PATH_SERT_FULLCHAIN}:/etc/nginx/certs/fullchain.pem
      - ${PATH_SERT_PRIVKEY}:/etc/nginx/certs/privkey.pem
    depends_on:
      - backend
