name: build-push
on:
  pull_request:
    branches: 
      - master
    types:
      - closed
jobs:
  docker:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: kartemdev/magic-list:latest
          build-args: |
            "API_HOST=${{ vars.API_HOST }}"
