name: build-push
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
jobs:
  docker:
    # if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    # environment: production
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/magiclist:latest
          build-args: |
            "API_HOST=${{ secrets.API_HOST }}"
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    # environment: production
      
    steps:
      - uses: actions/checkout@v3
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        env:
          PATH_SERT_FULLCHAIN: ${{ secrets.PATH_SERT_FULLCHAIN }}
          PATH_SERT_PRIVKEY: ${{ secrets.PATH_SERT_PRIVKEY }}
        with:
          envs: PATH_SERT_FULLCHAIN, PATH_SERT_PRIVKEY
          host: 147.45.138.133
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            chmod +x /usr/apps/frontend/entrypoint.sh
            /usr/apps/frontend/entrypoint.sh
