name: check-app
on:
  pull_request:
jobs:
  build-on-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 16.x ]
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: install packages
        run: npm ci
        working-directory: 'client'
      -
        name: build static files
        run: npm run build
        working-directory: 'client'
  lint-code:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      -
        name: Starting Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      -
        name: install packages
        run: npm ci
        working-directory: 'client'
      -
        name: linting js scripts
        run: npx lint-staged --diff="origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF}"
        working-directory: 'client'
